services:
  tiles:
    image: overv/openstreetmap-tile-server
    volumes:
      - osm-data:/data/database/
      - osm-tiles:/data/tiles/
    ports:
      - "8080:80"
      - "5432:5432"
    shm_size: 3G
    command: "run"
  routing:
    build: services/routing
    volumes:
      - osm-data:/data/database/
    ports:
      - "5433:5432"
    command: "run"

volumes:
  osm-data:
    external: true
  osm-tiles: 
    external: true