services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: nginx.conf
        target: /etc/nginx/nginx.conf
      - ./static:/usr/share/nginx/html
    network_mode: host
  pgbouncer:
    image: edoburu/pgbouncer
    environment:
      - DATABASE_URL=postgresql://nominatim:qaIACxO6wMR3@nominatim:5433/nominatim
      - AUTH_TYPE=scram-sha-256 # needed for connection to work with usual nominatim config?!
      - MAX_CLIENT_CONN=1000
      - POOL_MODE=session
    # set up bridge between pgbouncer and nominatim?
    #network_mode: host
    ports:
      - "5432:5432"
  nominatim:
    image: mediagis/nominatim:4.4
    volumes:
      - nominatim-data:/var/lib/postgresql/14/main
    # set up bridge between pgbouncer and nominatim?
    ports:
      - "8080:8080"
      - "5433:5433"
    environment:
      - PBF_PATH=/data/${REGION:?}.osm.pbf
      # needed otherwise it will fail to connect to the unix socket
      - NOMINATIM_DATABASE_DSN=pgsql:host=pgbouncer;port=5432;dbname=nominatim;user=nominatim;password=qaIACxO6wMR3
      # change postgres port, start postgres early to allow pgbouncer to setup
    command: sh -c "echo 'port = 5433' > /var/lib/postgresql/14/main/postgresql.auto.conf && service postgresql start && sleep 2 && /app/start.sh"
  # nominatim reverse geocoding is much better than photon
  photon:
    image: amazoncorretto:22.0.1-alpine3.19
    volumes:
      - /data:/data
      - nominatim-data:/photon
    ports:
      - "2322:2322"
    command: java -jar /data/photon-0.5.0.jar -data-dir /photon
  osrm-backend:
    image: ghcr.io/project-osrm/osrm-backend
    command: osrm-routed --algorithm mld /data/${REGION:?}.osrm
    volumes:
      - /data/osrm:/data
    ports:
      - "5000:5000"
  tileserver:
    image: maptiler/tileserver-gl:latest
    volumes:
      - /data/tiles:/data/tiles
      - /data/tileserver:/data
    ports:
      - "8081:8080"

volumes:
  nominatim-data:
    external: true
