services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: nginx.conf
        target: /etc/nginx/nginx.conf
      - ./static:/usr/share/nginx/html

  # auth microservice
  auth:
    build: .
    image: server
    command: auth
    ports:
      - "${AUTH_PORT:-8000}:80"

  # search microservice
  search:
    build: .
    image: server
    command: search
    ports:
      - "${SEARCH_PORT:-8001}:80"
  database:
    image: overv/openstreetmap-tile-server:latest
    command: run
    shm_size: 2g
    volumes:
      - osm-data:/data/database

  # tiles microservice
  tiles:
    build: .
    image: server
    command: tiles
    ports:
      - "${TILES_PORT:-8002}:80"
  tileserver:
    image: maptiler/tileserver-gl:latest
    volumes:
      - /data/tiles:/data/tiles
      - /data/tileserver:/data

  # route microservice
  route:
    build: .
    image: server
    command: route 
    ports:
      - "${ROUTE_PORT:-8003}:80"
  osrm-backend:
    image: ghcr.io/project-osrm/osrm-backend
    command: osrm-routed --algorithm mld /data/${REGION:?}.osrm
    volumes:
      - /data/osrm:/data

volumes:
  osm-data:
    external: true
