services:
  database:
    image: pgrouting/pgrouting:16-3.4-3.6.1
    volumes:
      - osm-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}

volumes:
  osm-data:
    external: true