services:
  app:
    image: .
    ports:
      - "8000:8000"
    command: ${SERVICE:-server}
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: nginx.conf
        target: /etc/nginx/nginx.conf
      - ./static:/usr/share/nginx/html
    network_mode: host
  nominatim:
    image: mediagis/nominatim:4.4
    volumes:
      - nominatim-data:/var/lib/postgresql/14/main
    ports:
      - "8080:8080"
      - "5432:5432"
    environment:
      - PBF_PATH=/data/${REGION:?}.osm.pbf
  osrm-backend:
    image: ghcr.io/project-osrm/osrm-backend
    command: osrm-routed --algorithm mld /data/${REGION:?}.osrm
    volumes:
      - /data/osrm:/data
    ports:
      - "5000:5000"
  tileserver:
    image: maptiler/tileserver-gl:latest
    volumes:
      - /data/tiles:/data/tiles
      - /data/tileserver:/data
    ports:
      - "8081:8080"

volumes:
  nominatim-data:
    external: true
