services:
  # loadbalancer
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
      - ./static:/usr/share/nginx/html
  
  # auth microservice
  auth:
    image: ubuntu:jammy
    volumes:
      - ./target/release:/bin
      - ./config.toml:/config.toml
    ports:
      - "${AUTH_PORT:?}:8000"
    command: auth

  # routing microservice
  routing:
    image: ubuntu:jammy
    volumes:
      - ./target/release:/bin
      - ./config.toml:/config.toml
    ports:
      - "${ROUTING_PORT:?}:8000"
    command: routing
  osrm-backend:
    image: ghcr.io/project-osrm/osrm-backend
    command: osrm-routed --algorithm mld /data/${REGION:?}.osrm
    volumes:
      - /data/osrm:/data
    ports:
      - "5000:5000"

  # tiles microservice
  tiles:
    image: ubuntu:jammy
    volumes:
      - ./target/release:/bin
      - ./config.toml:/config.toml
    ports:
      - "${TILES_PORT:?}:8000"
    command: tiles
  tileserver:
    image: maptiler/tileserver-gl:latest
    volumes:
      - /data/tiles:/data/tiles
      - /data/tileserver:/data
    ports:
      - "8081:8080"

#   nominatim:
#     image: mediagis/nominatim:4.4
#     volumes:
#       - nominatim-data:/var/lib/postgresql/14/main
#     ports:
#       - "8080:8080"
#       - "5432:5432"
#     environment:
#       - PBF_PATH=/data/${REGION:?}.osm.pbf
#   # nominatim reverse geocoding is much better than photon
#   photon:
#     image: amazoncorretto:22.0.1-alpine3.19
#     volumes:
#       - /data:/data
#       - nominatim-data:/photon
#     ports:
#       - "2322:2322"
#     command: java -jar /data/photon-0.5.0.jar -data-dir /photon

# volumes:
#   nominatim-data:
#     external: true
