services:
  map:
    image: overv/openstreetmap-tile-server
    volumes:
      - osm-data:/data/database/
      - osm-tiles:/data/tiles/
    ports:
      - "8080:80"
      - "5432:5432"
    shm_size: 3G
    command: "run"
  app: 
    build: .
    volumes:
      - .:/usr/src/final_project
    ports:
      - "80:80"

volumes:
  osm-data:
    external: true
  osm-tiles: 
    external: true