---
- name: Install aptitude
  hosts: all
  tasks:
    - name: Update apt and install aptitude
      ansible.builtin.apt:
        name: aptitude
        state: present
        update_cache: true

- name: Install pip3
  hosts: all
  tasks:
    - name: Update apt and install python3-pip
      ansible.builtin.apt:
        name: python3-pip
        state: present
        update_cache: true

- name: Install and configure docker
  hosts: all
  tasks:
    - name: Add Docker GPG apt Key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce
      ansible.builtin.apt:
        name: docker-ce
        state: present
        update_cache: true

    - name: Install Docker SDK for Python
      ansible.builtin.pip:
        name: docker
        state: present

- name: Build binaries
  hosts: localhost
  tasks:
    - name: Build binaries
      ansible.builtin.command:
        cmd: cargo build --release
        creates: ./target/release

- name: Setup routing microservice
  hosts: routing
  tasks:
    - name: Copy routing binary
      ansible.builtin.copy:
        src: ./target/release/routing
        dest: /bin
        mode: '0755'

    - name: Copy config file
      ansible.builtin.copy:
        src: ./config.toml
        dest: .
        mode: '0644'

    - name: Copy OSRM data
      ansible.builtin.copy:
        src: /data/osrm/
        dest: /data/osrm/
        mode: '0644'

    - name: Start OSRM service
      community.docker.docker_container:
        name: osrm
        image: ghcr.io/project-osrm/osrm-backend
        command: osrm-routed --algorithm mld /data/{{ REGION }}.osrm
        volumes:
          - /data/osrm:/data
        network_mode: host

    - name: Start routing service
      community.docker.docker_container:
        name: routing
        image: ubuntu:jammy
        command: routing
        volumes:
          - /bin:/bin
          - ./config.toml:/config.toml
        network_mode: host
