---
- name: Install aptitude
  hosts: all
  tasks:
    - name: Update apt and install aptitude
      ansible.builtin.apt:
        name: aptitude
        state: present
        update_cache: true

- name: Install pip3
  hosts: all
  tasks:
    - name: Update apt and install python3-pip
      ansible.builtin.apt:
        name: python3-pip
        state: present
        update_cache: true

- name: Install and configure docker
  hosts: all
  tasks:
    - name: Add Docker GPG apt Key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce
      ansible.builtin.apt:
        name: docker-ce
        state: present
        update_cache: true

    - name: Install Docker SDK for Python
      ansible.builtin.pip:
        name:
          - docker
          - docker-compose
        state: present

- name: Check Docker image exists
  hosts: localhost
  tasks:
    - name: Check Docker image exists
      ansible.builtin.stat:
        path: ./server.tar.gz
      register: result

- name: Build and save Docker image
  hosts: localhost
  tasks:
    - name: Build Docker image
      community.docker.docker_image:
        state: present
        source: build
        build:
          path: .
        name: server
        tag: latest
      when: not result.stat.exists

    - name: Save Docker image
      ansible.builtin.command:
        cmd: docker save server:latest -o ./server.tar
        creates: ./server.tar
      when: not result.stat.exists

    - name: Compress Docker image
      community.general.archive:
        path: ./server.tar
        dest: ./server.tar.gz
        format: gz
        mode: '0644'
        remove: true
      when: not result.stat.exists

- name: Copy and load Docker image
  hosts: all
  tasks:
    - name: Copy and unarchive Docker image
      ansible.builtin.unarchive:
        copy: true
        src: ./server.tar.gz
        dest: /tmp
        mode: '0644'

    - name: Load Docker image
      community.docker.docker_image:
        name: server
        source: load
        load_path: /tmp/server.tar

- name: Setup routing microservice
  hosts: routing
  tasks:
    - name: Copy docker-compose file
      ansible.builtin.copy:
        src: ./services/routing/
        dest: /opt/routing/
        mode: '0644'

    - name: Copy OSRM data
      ansible.builtin.copy:
        src: /data/osrm/
        dest: /data/osrm/
        mode: '0644'

    - name: Start routing microservice
      community.docker.docker_compose_v2:
        project_name: routing
        project_src: /opt/routing
