services:
  search:
    image: ubuntu:latest
    command: search
    ports:
      - "${SEARCH_PORT:-8001}:80"
    volumes:
      - /bin:/bin
      - ./config.toml:/config.toml
    depends_on:
      database:
        condition: service_healthy   

  database:
    image: overv/openstreetmap-tile-server:latest
    command: run
    shm_size: 2g
    volumes:
      - osm-data:/data/database
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "renderer", "-d", "gis"]
      interval: 1m
      timeout: 10s
      retries: 1
      start_period: 1m

volumes:
  osm-data:
    external: true
  