version: "3"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      # docker will create a directory instead of the file if not done this way
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
      - ../../static:/usr/share/nginx/html
    extra_hosts:
      # access Rust server running on host
      - "host.docker.internal:host-gateway"
    ulimits:
      nofile:
          soft: 65536
          hard: 65536

  database:
    image: overv/openstreetmap-tile-server:latest
    command: run
    shm_size: 2g
    volumes:
      - osm-data:/data/database
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "renderer", "-d", "gis"]
      interval: 1m
      timeout: 10s
      retries: 1
      start_period: 1m
    ulimits:
      nofile:
          soft: 65536
          hard: 65536

  tileserver:
    image: maptiler/tileserver-gl:latest
    volumes:
      - /data/tiles:/data/tiles
      - /data/tileserver:/data
    ports:
      - 8081:8080

  osrm-backend:
    image: ghcr.io/project-osrm/osrm-backend
    command: osrm-routed --algorithm mld /data/${REGION:?}.osrm
    volumes:
      - /data/osrm:/data
    ports:
      - 5000:5000

  cache: 
    image: redis:alpine
    command: redis-server --appendonly no --maxmemory 8gb --save 60 1 --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    volumes:
      - redis-db:/data
    ulimits:
      nofile:
          soft: 65536
          hard: 65536

volumes:
  redis-db:
    external: true
  osm-data:
    external: true
