services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: nginx.conf
        target: /etc/nginx/nginx.conf
      - ../../../static:/usr/share/nginx/html
    depends_on:
      - auth
      - search
      - tiles
      - route

  # auth microservice
  auth:
    build: .
    image: server
    command: auth
    ports:
      - "${AUTH_PORT:-8000}:80"

  # search microservice
  search:
    build: .
    image: server
    command: search
    ports:
      - "${SEARCH_PORT:-8001}:80"
    depends_on:
      database:
        condition: service_healthy
  database:
    image: overv/openstreetmap-tile-server:latest
    command: run
    shm_size: 2g
    volumes:
      - osm-data:/data/database
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "renderer", "-d", "gis"]
      interval: 1m
      timeout: 10s
      retries: 1
      start_period: 1m

  # tiles microservice
  tiles:
    build: .
    image: server
    command: tiles
    ports:
      - "${TILES_PORT:-8002}:80"
    depends_on:
      - tileserver
  tileserver:
    image: maptiler/tileserver-gl:latest
    volumes:
      - /data/tiles:/data/tiles
      - /data/tileserver:/data

  # route microservice
  route:
    build: .
    image: server
    command: route 
    ports:
      - "${ROUTE_PORT:-8003}:80"
    depends_on:
      - osrm-backend
  osrm-backend:
    image: ghcr.io/project-osrm/osrm-backend
    command: osrm-routed --algorithm mld /data/${REGION:?}.osrm
    volumes:
      - /data/osrm:/data
      
  cache: 
    image: redis:alpine
    command: redis-server --appendonly no --maxmemory 8gb --save 60 1 --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    volumes:
      - redis-db:/data

volumes:
  redis-db:
    external: true
  osm-data:
    external: true
